---
- name: Install required package (Linux)
  loop:
    - wget
    - tar
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  when: ansible_system == "Linux"

- name: Install Syncthing binary (Linux)
  changed_when: False
  ansible.builtin.shell:
    cmd: >-
      mkdir -p ~/syncthing &&
      wget https://github.com/syncthing/syncthing/releases/download/v{{syncthing_version}}/syncthing-linux-{{syncthing_architecture}}-v{{syncthing_version}}.tar.gz -O ~/syncthing.tar.gz &&
      tar -xvzf syncthing.tar.gz -C syncthing --strip-components=1 &&
      rm -rf /usr/local/bin/syncthing &&
      mv ~/syncthing/syncthing /usr/local/bin/ &&
      chmod +x /usr/local/bin/syncthing &&
      rm -rf ~/syncthing.tar.gz &&
      rm -rf ~/syncthing
  when: ansible_system == "Linux"

- name: Install Syncthing service config (systemd)
  ansible.builtin.template:
    src: "systemd/syncthing@.service.j2"
    dest: /usr/lib/systemd/system/syncthing@.service
    mode: "0644"
  when:
    - ansible_system == "Linux"
    - ansible_service_mgr == "systemd"
